source "https://rubygems.org"
ruby ">= 3.2.0"
gem "rails", "~> 8.1.3", ">= 8.1.3.1"
gem "pg", "~> 1.6"
gem "puma", "~> 7.0"
gem "propshaft", "~> 1.1"
gem "importmap-rails", "~> 2.2"
gem "turbo-rails", "~> 2.0"
gem "stimulus-rails", "~> 1.3"
gem "rubyzip", "~> 3.0"
gem "omniauth_openid_connect", "~> 0.8"
gem "omniauth-rails_csrf_protection", "~> 2.0"
# Rails 8.1 calls JSON.parse with an options hash; JSON 3 requires keywords.
gem "json", ">= 2.9", "< 3"
