default: &default
  adapter: postgresql
  encoding: unicode
  connect_timeout: 3
  checkout_timeout: 3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://certui:certui@127.0.0.1:55432/certui_development") %>
development:
  <<: *default
test:
  <<: *default
  url: <%= ENV.fetch("TEST_DATABASE_URL", "postgresql://certui:certui@127.0.0.1:55432/certui_test") %>
production:
  <<: *default
