require "json"

# A synthetic health response for the disposable screenshot stack only.
# Inventory mappings are generated by seed.rb, not by this endpoint.
run lambda { |env|
  request = Rack::Request.new(env)
  if request.post? && request.path_info == "/pdb/query/v4" &&
      JSON.parse(request.body.read).fetch("query") == "nodes[certname] { limit 1 }"
    [200, { "content-type" => "application/json", "x-records" => "1" },
      [JSON.generate([{ certname: "web01.example.test" }])]]
  else
    [400, { "content-type" => "application/json" }, ['{"error":"Unsupported demo query"}']]
  end
}
